### ISSUE TITLE
not working on debian 8.3

### ISSUE THREAD

**Issue by Moorviper** [hopglass/node-respondd#1]
On Debian 8.3
cat /etc/debian_version 
8.3

i get:

/opt/node-respondd/respondd:75
    return os.networkInterfaces()[iface].filter((a) => a.family == "IPv6").map
                                                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by tobias-theobald** [comment]
I'm guessing the nodejs version in Debian is too old (v0.10.29 currently) and doesn't support lambdas yet. https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions gives you hints on how to install a newer version in debian. 4.x and 6.x both seem to work.
